package mage

import (
	"slices"
	"time"

	"github.com/isfir/wowsims-turtle/sim/core"
	"github.com/isfir/wowsims-turtle/sim/core/stats"
)

///////////////////////////////////////////////////////////////////////////
//                            Tier 0/0.5
///////////////////////////////////////////////////////////////////////////

var ItemSetMagistersRegalia = core.NewItemSet(core.ItemSet{
	Name: "Magister's Regalia",
	ID:   181,
	Bonuses: map[int32]core.ApplyEffect{
		// +200 Armor.
		2: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.Armor, 200)
		},
		// Increases damage and healing done by magical spells and effects by up to 23.
		4: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPower, 23)
		},
		// When struck in combat has a chance of freezing the attacker in place for 3 sec.
		// 6: func(agent core.Agent) {
		// Not implemented in sim.
		// },
		// +8 All Resistances.
		8: func(agent core.Agent) {
			agent.GetCharacter().AddResistances(8)
		},
	},
})

var ItemSetSorcerersRegalia = core.NewItemSet(core.ItemSet{
	Name: "Sorcerer's Regalia",
	ID:   517,
	Bonuses: map[int32]core.ApplyEffect{
		// +8 All Resistances.
		2: func(agent core.Agent) {
			agent.GetCharacter().AddResistances(8)
		},
		// When struck in combat has a chance of freezing the attacker in place for 3 sec.
		// 4: func(agent core.Agent) {
		// Not implemented in sim.
		// },
		// Increases damage and healing done by magical spells and effects by up to 23.
		6: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPower, 23)
		},
		// +200 Armor.
		8: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.Armor, 200)
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Tier 1
///////////////////////////////////////////////////////////////////////////

var ItemSetArcanistsRegalia = core.NewItemSet(core.ItemSet{
	Name: "Arcanist's Regalia",
	ID:   201,
	Bonuses: map[int32]core.ApplyEffect{
		// Increases damage and healing done by magical spells and effects by up to 18.
		3: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPower, 18)
		},
		// Decreases the magical resistances of your spell targets by 10.
		5: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPenetration, 10)
		},
		// Decreases the threat generated by your spells by 15%.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Subtlety (Arcanist's Regalia)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range mage.Spellbook {
						if spell.Flags.Matches(SpellFlagMage) {
							spell.ThreatMultiplier *= 0.85
						}
					}
				},
			})
		},
	},
})

var ItemSetArcanistsVestments = core.NewItemSet(core.ItemSet{
	Name: "Arcanist's Vestments",
	ID:   657,
	Bonuses: map[int32]core.ApplyEffect{
		// Increases your attack and casting speed by 2%.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.AddStats(stats.Stats{
				stats.MeleeHaste: 2,
				stats.SpellHaste: 2,
			})
			mage.MultiplyCastSpeed(1.02)
		},
		// Your damaging Arcane spells have a 10% chance to restore 50 mana over 5 sec.
		5: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			actionID := core.ActionID{SpellID: 52569}
			manaMetrics := mage.NewManaMetrics(actionID)

			revitalizeSpell := mage.RegisterSpell(core.SpellConfig{
				ActionID: actionID,
				Flags:    core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagHelpful,
				Hot: core.DotConfig{
					SelfOnly: true,
					Aura: core.Aura{
						Label: "Revitalize",
					},
					NumberOfTicks: 5,
					TickLength:    time.Second,
					OnTick: func(sim *core.Simulation, target *core.Unit, dot *core.Dot) {
						mage.AddMana(sim, 10, manaMetrics)
					},
				},
				ApplyEffects: func(sim *core.Simulation, _ *core.Unit, spell *core.Spell) {
					spell.SelfHot().Apply(sim)
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Revitalize Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !result.Landed() {
						return
					}
					if !spell.Flags.Matches(SpellFlagMage) || !spell.SpellSchool.Matches(core.SpellSchoolArcane) || !spell.ProcMask.Matches(core.ProcMaskSpellDamage) {
						return
					}
					if sim.Proc(0.10, "Revitalize") {
						revitalizeSpell.Cast(sim, &mage.Unit)
					}
				},
			})
		},
		// Your Arcane Rupture affects all Arcane spells that deal damage.
		8: func(agent core.Agent) {
			// Implemented in arcane_rupture.go
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Zul'Gurub
///////////////////////////////////////////////////////////////////////////

var ItemSetIllusionistsAttire = core.NewItemSet(core.ItemSet{
	Name: "Illusionist's Attire",
	ID:   482,
	Bonuses: map[int32]core.ApplyEffect{
		// Increases damage and healing done by magical spells and effects by up to 12.
		2: func(agent core.Agent) {
			agent.GetCharacter().AddStat(stats.SpellPower, 12)
		},
		// Decreases the mana cost of Arcane Intellect and Arcane Brilliance by 5%.
		// 3: func(agent core.Agent) {
		// No implementation in sim.
		// },
		// Reduces the casting time of your Flamestrike spell by 0.5 sec.
		5: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label:    "Improved Flamestrike",
				ActionID: core.ActionID{SpellID: 24491},
				Duration: core.NeverExpires,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range mage.Spellbook {
						if spell.SpellCode == SpellCode_MageFlamestrike {
							spell.DefaultCast.CastTime -= 500 * time.Millisecond
						}
					}
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Ruins of Ahn'Qiraj
///////////////////////////////////////////////////////////////////////////

var ItemSetTrappingsOfVaultedSecrets = core.NewItemSet(core.ItemSet{
	Name: "Trappings of Vaulted Secrets",
	ID:   504,
	Bonuses: map[int32]core.ApplyEffect{
		// 15% increase to the total damage absorbed by Mana Shield.
		// 2: func(agent core.Agent) {
		// Not implemented: Mana Shield is not implemented in sim.
		// },
		// Using a Mana Gem increases your damage and healing from magical spells and effects by up to 60 for 10 sec.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			crystalInfusionAura := mage.NewTemporaryStatsAura(
				"Crystal Infusion",
				core.ActionID{SpellID: 52691},
				stats.Stats{stats.SpellPower: 60},
				time.Second*10,
			)

			mage.RegisterAura(core.Aura{
				Label: "Crystal Infusion Trigger",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, manaGem := range mage.ManaGem {
						if manaGem == nil {
							continue
						}

						wrappedSpell := manaGem
						oldApplyEffects := wrappedSpell.ApplyEffects
						wrappedSpell.ApplyEffects = func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
							oldApplyEffects(sim, target, spell)
							crystalInfusionAura.Activate(sim)
						}
					}
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Tier 2
///////////////////////////////////////////////////////////////////////////

var ItemSetNetherwindRegalia = core.NewItemSet(core.ItemSet{
	Name: "Netherwind Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// Reduces the threat generated by your Scorch, Arcane Missiles, Fireball, and Frostbolt spells.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Friendly Nukes",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, spell := range mage.Spellbook {
						if spell.SpellCode == SpellCode_MageFireball || spell.SpellCode == SpellCode_MageArcaneMissilesTick {
							spell.FlatThreatBonus -= 20
						}
						if spell.SpellCode == SpellCode_MageScorch || spell.SpellCode == SpellCode_MageFrostbolt {
							spell.FlatThreatBonus -= 100
						}
					}
				},
			})
		},
		// Increases the radius of Arcane Explosion, Flamestrike, and Blizzard by 25%.
		// 5: func(agent core.Agent) {
		// No implementation in sim
		// },
		// 10% chance after casting Arcane Missiles, Fireball, or Frostbolt that your next spell with a casting time under 10 seconds cast instantly.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			actionID := core.ActionID{SpellID: 22008}

			affectedSpells := []*core.Spell{}
			netherwindFocusAura := mage.RegisterAura(core.Aura{
				Label:    "Netherwind Focus",
				ActionID: actionID,
				Duration: time.Second * 10,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for spellIdx := range mage.Spellbook {
						if spell := mage.Spellbook[spellIdx]; spell.DefaultCast.CastTime > 0 && spell.DefaultCast.CastTime <= 10*time.Second {
							affectedSpells = append(affectedSpells, spell)
						}
					}
				},
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					core.Each(affectedSpells, func(spell *core.Spell) {
						spell.CastTimeMultiplier -= 1
					})
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					core.Each(affectedSpells, func(spell *core.Spell) {
						spell.CastTimeMultiplier += 1
					})
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if !slices.Contains(affectedSpells, spell) {
						return
					}
					if spell.CurCast.CastTime > 0 { //Returns if you are midcast when your aura procs from landing to prevent instant consumption
						return
					}
					aura.Deactivate(sim)
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Netherwind Focus - Proc Aura",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if spell.SpellCode == SpellCode_MageArcaneMissiles || spell.SpellCode == SpellCode_MageFireball || spell.SpellCode == SpellCode_MageFrostbolt {
						if sim.Proc(0.10, "Netherwind Focus Proc") {
							netherwindFocusAura.Activate(sim)
						}
					}
				},
			})
		},
	},
})

var ItemSetNetherwindVestments = core.NewItemSet(core.ItemSet{
	Name: "Netherwind Vestments",
	ID:   658,
	Bonuses: map[int32]core.ApplyEffect{
		// Mage Armor increases resistance by an additional 15 to all magic schools and allows an additional 15% of your mana regeneration to continue while casting.
		3: func(agent core.Agent) {
			// Intentionally not reimplemented here, Mage Armor bonus is already handled globally in armor logic since you can keep bonus after removing set.
		},
		// Your critical strikes with damaging Arcane spells increase your casting speed by 5% for 6 sec.
		5: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			cosmicResidueAura := mage.RegisterAura(core.Aura{
				Label:    "Cosmic Residue",
				ActionID: core.ActionID{SpellID: 52571},
				Duration: time.Second * 6,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.MultiplyCastSpeed(1.05)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.MultiplyCastSpeed(1 / 1.05)
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Cosmic Residue Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !result.DidCrit() {
						return
					}
					if !spell.Flags.Matches(SpellFlagMage) || !spell.SpellSchool.Matches(core.SpellSchoolArcane) {
						return
					}
					cosmicResidueAura.Activate(sim)
				},
			})
		},
		// Arcane Surge increases the damage of your spells and effects by up to 40 for 8 sec.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			oversurgeAura := mage.NewTemporaryStatsAura(
				"Oversurge",
				core.ActionID{SpellID: 52572},
				stats.Stats{stats.SpellDamage: 40},
				time.Second*8,
			)

			mage.RegisterAura(core.Aura{
				Label:    "Oversurge Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if result.Landed() && spell.SpellCode == SpellCode_MageArcaneSurge {
						oversurgeAura.Activate(sim)
					}
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Temple of Ahn'Qiraj
///////////////////////////////////////////////////////////////////////////

var ItemSetEnigmaRegalia = core.NewItemSet(core.ItemSet{
	Name: "Enigma Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// Your Blizzard spell has a 30% chance to be uninterruptible.
		// 3: func(agent core.Agent) {
		// No implementation in sim
		// },
		// Grants +5% increased spell hit chance for 20 sec when one of your spells is resisted.
		5: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			actionID := core.ActionID{SpellID: 26129}

			enigmasAnswerAura := mage.RegisterAura(core.Aura{
				Label:     "Enigma's Answer",
				ActionID:  actionID,
				Duration:  time.Second * 20,
				MaxStacks: 4,
				OnStacksChange: func(aura *core.Aura, sim *core.Simulation, oldStacks, newStacks int32) {
					mage.AddStatDynamic(sim, stats.SpellHit, float64(-5*oldStacks))
					mage.AddStatDynamic(sim, stats.SpellHit, float64(5*newStacks))
				},
			})

			// Wowhead suggests this does not work on all spell (imp scorch and arcane missiles).  Would need testing to confirm.
			mage.RegisterAura(core.Aura{
				Label:    "Enigma Resist Bonus",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if result.Outcome.Matches(core.OutcomeMiss) && spell.ProcMask.Matches(core.ProcMaskDirect) {
						enigmasAnswerAura.Activate(sim)
						enigmasAnswerAura.AddStack(sim)
					}
				},
			})
		},
	},
})

var ItemSetEnigmaVestments = core.NewItemSet(core.ItemSet{
	Name: "Enigma Vestments",
	ID:   659,
	Bonuses: map[int32]core.ApplyEffect{
		// When any of your Arcane spells is partially or fully resisted, the cooldown of your next Evocation is reduced by 10 sec. Stacks up to 12 times.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			var baseCooldown time.Duration
			evocationMasteryAura := mage.RegisterAura(core.Aura{
				Label:     "Evocation Mastery",
				ActionID:  core.ActionID{SpellID: 52591},
				Duration:  core.NeverExpires,
				MaxStacks: 12,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					baseCooldown = 0
				},
				OnStacksChange: func(aura *core.Aura, sim *core.Simulation, oldStacks, newStacks int32) {
					if mage.Evocation == nil {
						return
					}

					if oldStacks == 0 && newStacks > 0 {
						baseCooldown = mage.Evocation.CD.Duration
					}

					if newStacks == 0 {
						if baseCooldown != 0 {
							mage.Evocation.CD.Duration = baseCooldown
						}
						return
					}

					newDuration := max(baseCooldown-time.Duration(newStacks)*10*time.Second, 0)
					mage.Evocation.CD.Duration = newDuration
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					if spell == mage.Evocation {
						aura.Deactivate(sim)
					}
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Evocation Mastery Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !spell.Flags.Matches(SpellFlagMage) || !spell.SpellSchool.Matches(core.SpellSchoolArcane) || !spell.ProcMask.Matches(core.ProcMaskSpellDamage) {
						return
					}
					if !result.Outcome.Matches(core.OutcomeResisted) {
						return
					}

					evocationMasteryAura.Activate(sim)
					evocationMasteryAura.AddStack(sim)
				},
			})
		},
		// Upon fully channeling Evocation, the damage of your magical spells and effects is increased by 10% and their mana costs is increased by 10% for 8 sec.
		5: func(agent core.Agent) {
			// Implemented in evocation.go
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Tier 3
///////////////////////////////////////////////////////////////////////////

var ItemSetFrostfireRegalia = core.NewItemSet(core.ItemSet{
	Name: "Frostfire Regalia",
	Bonuses: map[int32]core.ApplyEffect{
		// Reduces cooldown on your Evocation by 1 minute.
		2: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			mage.RegisterAura(core.Aura{
				Label: "Evocation (Frostfire Regalia)",
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					if mage.Evocation != nil {
						mage.Evocation.CD.Duration -= time.Second * 60
					}
				},
			})
		},
		// Gives your Mage Armor a chance when struck by a harmful spell to increase resistance against that school of magic by 35 for 30 sec. (Proc chance: 20%)
		// Fire - https://www.wowhead.com/classic/spell=28765/fire-resistance
		// Frost - https://www.wowhead.com/classic/spell=28766/frost-resistance
		// Nature - https://www.wowhead.com/classic/spell=28768/nature-resistance
		// Shadow - https://www.wowhead.com/classic/spell=28769/shadow-resistance
		// Arcane - https://www.wowhead.com/classic/spell=28770/arcane-resistance

		4: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			fireWardingAura := mage.RegisterAura(core.Aura{
				Label:    "Fire Resistance",
				ActionID: core.ActionID{SpellID: 28765},
				Duration: time.Second * 30,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.FireResistance, 35)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.FireResistance, -35)
				},
			})

			frostWardingAura := mage.RegisterAura(core.Aura{
				Label:    "Frost Resistance",
				ActionID: core.ActionID{SpellID: 28766},
				Duration: time.Second * 30,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.FrostResistance, 35)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.FrostResistance, -35)
				},
			})

			natureWardingAura := mage.RegisterAura(core.Aura{
				Label:    "Nature Resistance",
				ActionID: core.ActionID{SpellID: 28768},
				Duration: time.Second * 30,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.NatureResistance, 35)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.NatureResistance, -35)
				},
			})

			shadowWardingAura := mage.RegisterAura(core.Aura{
				Label:    "Shadow Resistance",
				ActionID: core.ActionID{SpellID: 28769},
				Duration: time.Second * 30,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.ShadowResistance, 35)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.ShadowResistance, -35)
				},
			})

			arcaneWardingAura := mage.RegisterAura(core.Aura{
				Label:    "Arcane Resistance",
				ActionID: core.ActionID{SpellID: 28770},
				Duration: time.Second * 30,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.ArcaneResistance, 35)
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.AddStatDynamic(sim, stats.ArcaneResistance, -35)
				},
			})

			// Wowhead suggests this does not work on all spell (imp scorch and arcane missiles).  Would need testing to confirm.
			mage.RegisterAura(core.Aura{
				Label:    "Adaptive Warding",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if sim.Proc(0.20, "Adaptive Warding") {
						if spell.SpellSchool.Matches(core.SpellSchoolFire) {
							fireWardingAura.Activate(sim)
							return
						}
						if spell.SpellSchool.Matches(core.SpellSchoolFrost) {
							frostWardingAura.Activate(sim)
							return
						}
						if spell.SpellSchool.Matches(core.SpellSchoolNature) {
							natureWardingAura.Activate(sim)
							return
						}
						if spell.SpellSchool.Matches(core.SpellSchoolShadow) {
							shadowWardingAura.Activate(sim)
							return
						}
						if spell.SpellSchool.Matches(core.SpellSchoolArcane) {
							arcaneWardingAura.Activate(sim)
							return
						}
					}
				},
			})
		},
		// Your damage spells have a chance to cause your target to take up to 200 increased damage from subsequent spells. (Proc chance: 20%)
		6: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			procAuras := mage.NewEnemyAuraArray(func(target *core.Unit) *core.Aura {
				return target.GetOrRegisterAura(core.Aura{
					Label:     "Elemental Vulnerability",
					ActionID:  core.ActionID{SpellID: 28772},
					Duration:  time.Second * 30,
					MaxStacks: 1,

					OnGain: func(aura *core.Aura, sim *core.Simulation) {
						aura.SetStacks(sim, aura.MaxStacks)

						for si := stats.SchoolIndexArcane; si < stats.SchoolLen; si++ {
							aura.Unit.PseudoStats.SchoolBonusDamageTaken[si] += 200
						}
					},
					OnExpire: func(aura *core.Aura, sim *core.Simulation) {
						for si := stats.SchoolIndexArcane; si < stats.SchoolLen; si++ {
							aura.Unit.PseudoStats.SchoolBonusDamageTaken[si] -= 200
						}
					},
					OnSpellHitTaken: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
						// OnCastComplete is called after OnSpellHitDealt / etc, so don't deactivate if it was just activated.
						if aura.RemainingDuration(sim) == aura.Duration {
							return
						}

						if result.Landed() && spell.ProcMask.Matches(core.ProcMaskDirect) {
							aura.RemoveStack(sim)
						}
					},
				})
			})

			handler := func(sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
				procAuras.Get(result.Target).Activate(sim)
			}

			core.MakeProcTriggerAura(&mage.Unit, core.ProcTrigger{
				ActionID:   core.ActionID{SpellID: 28771},
				Name:       "Elemental Vulnerability",
				Callback:   core.CallbackOnSpellHitDealt,
				Outcome:    core.OutcomeLanded,
				ProcMask:   core.ProcMaskSpellDamage,
				ProcChance: 0.2,
				Handler:    handler,
			})
		},
		// Your damage spells have a chance to displace you, causing the next spell cast to generate no threat. (Proc chance: 15%)
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			notThereAura := mage.RegisterAura(core.Aura{
				Label:    "Not There",
				ActionID: core.ActionID{SpellID: 28762},
				Duration: time.Second * 8,
				OnGain: func(aura *core.Aura, sim *core.Simulation) {
					mage.PseudoStats.ThreatMultiplier -= 1
				},
				OnExpire: func(aura *core.Aura, sim *core.Simulation) {
					mage.PseudoStats.ThreatMultiplier += 1
				},
				OnCastComplete: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell) {
					// OnCastComplete is called after OnSpellHitDealt / etc, so don't deactivate if it was just activated.
					if aura.RemainingDuration(sim) == aura.Duration {
						return
					}
					aura.Deactivate(sim)
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "NotThere",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if sim.Proc(0.15, "Not There") && result.Landed() && spell.ProcMask.Matches(core.ProcMaskDirect) {
						notThereAura.Activate(sim)
					}
				},
			})
		},
	},
})

var ItemSetFrostfireVestments = core.NewItemSet(core.ItemSet{
	Name: "Frostfire Vestments",
	ID:   660,
	Bonuses: map[int32]core.ApplyEffect{
		// When your Mana Shield is broken, it erupts violently, dealing Arcane damage equal to 20% of the absorbed damage to all targets within 8 yards.
		// 2: func(agent core.Agent) {
		// Not implemented: Mana Shield is not implemented in sim.
		// },
		// Your Arcane Rupture and Arcane Surge critical strikes displace enemies within 8 yards of the target, reducing all their resistances by 25 for 8 sec.
		4: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			realityFractureAuras := mage.NewEnemyAuraArray(func(target *core.Unit) *core.Aura {
				return target.GetOrRegisterAura(core.Aura{
					Label:    "Reality Fracture",
					ActionID: core.ActionID{SpellID: 52593},
					Duration: time.Second * 8,
					OnGain: func(aura *core.Aura, sim *core.Simulation) {
						aura.Unit.AddResistancesDynamic(sim, -25)
					},
					OnExpire: func(aura *core.Aura, sim *core.Simulation) {
						aura.Unit.AddResistancesDynamic(sim, 25)
					},
				})
			})

			mage.RegisterAura(core.Aura{
				Label:    "Reality Fracture Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !result.DidCrit() {
						return
					}
					if spell.SpellCode != SpellCode_MageArcaneRupture && spell.SpellCode != SpellCode_MageArcaneSurge {
						return
					}

					for _, target := range sim.Encounter.TargetUnits {
						realityFractureAuras.Get(target).Activate(sim)
					}
				},
			})
		},
		// While Arcane Power is active, your Arcane spell critical strikes restore 3% of your maximum mana.
		6: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()
			manaMetrics := mage.NewManaMetrics(core.ActionID{SpellID: 52581})

			mage.RegisterAura(core.Aura{
				Label:    "Coalesced Mana",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if mage.ArcanePowerAura == nil || !mage.ArcanePowerAura.IsActive() {
						return
					}
					if !result.DidCrit() {
						return
					}
					if !spell.Flags.Matches(SpellFlagMage) || !spell.SpellSchool.Matches(core.SpellSchoolArcane) {
						return
					}

					mage.AddMana(sim, mage.MaxMana()*0.03, manaMetrics)
				},
			})
		},
		// Whenever your damaging Arcane spells are partially or fully resisted, the damage of your next direct spell cast within 6 sec is increased by 10%.
		8: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			var riftFeedbackAura *core.Aura
			riftFeedbackAura = mage.RegisterAura(core.Aura{
				Label:    "Rift Feedback",
				ActionID: core.ActionID{SpellID: 52590},
				Duration: time.Second * 6,
				OnInit: func(aura *core.Aura, sim *core.Simulation) {
					for _, registeredSpell := range mage.Spellbook {
						if registeredSpell == nil ||
							!registeredSpell.Flags.Matches(SpellFlagMage) ||
							!registeredSpell.ProcMask.Matches(core.ProcMaskDirect) ||
							registeredSpell.Flags.Matches(core.SpellFlagChanneled|core.SpellFlagPassiveSpell) ||
							registeredSpell.SpellCode == SpellCode_MageArcaneMissilesTick {
							continue
						}

						wrappedSpell := registeredSpell
						oldApplyEffects := wrappedSpell.ApplyEffects
						wrappedSpell.ApplyEffects = func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
							if !riftFeedbackAura.IsActive() {
								oldApplyEffects(sim, target, spell)
								return
							}

							spell.ImpactDamageMultiplierAdditive += 0.10
							oldApplyEffects(sim, target, spell)
							spell.ImpactDamageMultiplierAdditive -= 0.10

							// Keep a fresh proc from the consuming spell itself.
							if riftFeedbackAura.RemainingDuration(sim) == riftFeedbackAura.Duration {
								return
							}
							riftFeedbackAura.Deactivate(sim)
						}
					}
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Rift Feedback Trigger",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !spell.Flags.Matches(SpellFlagMage) || !spell.SpellSchool.Matches(core.SpellSchoolArcane) || !spell.ProcMask.Matches(core.ProcMaskSpellDamage) {
						return
					}
					if !result.Outcome.Matches(core.OutcomeResisted) {
						return
					}

					riftFeedbackAura.Activate(sim)
				},
			})
		},
	},
})

///////////////////////////////////////////////////////////////////////////
//                            Tower of Karazhan
///////////////////////////////////////////////////////////////////////////

var ItemSetRegaliaOfTheGuardian = core.NewItemSet(core.ItemSet{
	Name: "Regalia of the Guardian",
	ID:   684,
	Bonuses: map[int32]core.ApplyEffect{
		// Initial hits from Flamestrike, Cone of Cold, Frost Nova, Blast Wave, and Arcane Explosion have a chance to trigger a rewind effect. On rewind, Arcane
		// spells deal 10% additional damage, and Frost and Fire spells deal 20% additional damage.
		3: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			arcaneDamage := 0.0
			fireDamage := 0.0
			frostDamage := 0.0

			arcaneProc := mage.RegisterSpell(core.SpellConfig{
				ActionID:    core.ActionID{SpellID: 52597},
				SpellSchool: core.SpellSchoolArcane,
				DefenseType: core.DefenseTypeMagic,
				ProcMask:    core.ProcMaskEmpty,
				Flags:       core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagIgnoreModifiers,

				DamageMultiplier: 1,
				ThreatMultiplier: 1,

				ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
					spell.CalcAndDealDamage(sim, target, arcaneDamage, spell.OutcomeAlwaysHit)
				},
			})

			fireProc := mage.RegisterSpell(core.SpellConfig{
				ActionID:    core.ActionID{SpellID: 52733},
				SpellSchool: core.SpellSchoolFire,
				DefenseType: core.DefenseTypeMagic,
				ProcMask:    core.ProcMaskEmpty,
				Flags:       core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagIgnoreModifiers,

				DamageMultiplier: 1,
				ThreatMultiplier: 1,

				ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
					spell.CalcAndDealDamage(sim, target, fireDamage, spell.OutcomeAlwaysHit)
				},
			})

			frostProc := mage.RegisterSpell(core.SpellConfig{
				ActionID:    core.ActionID{SpellID: 52734},
				SpellSchool: core.SpellSchoolFrost,
				DefenseType: core.DefenseTypeMagic,
				ProcMask:    core.ProcMaskEmpty,
				Flags:       core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagIgnoreModifiers,

				DamageMultiplier: 1,
				ThreatMultiplier: 1,

				ApplyEffects: func(sim *core.Simulation, target *core.Unit, spell *core.Spell) {
					spell.CalcAndDealDamage(sim, target, frostDamage, spell.OutcomeAlwaysHit)
				},
			})

			// TODO: Add Cone of Cold and Frost Nova
			eligibleSpellCodes := []int32{
				SpellCode_MageFlamestrike,
				SpellCode_MageBlastWave,
				SpellCode_MageArcaneExplosion,
			}

			mage.RegisterAura(core.Aura{
				Label:    "Magic Mirror Passive",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !result.Landed() {
						return
					}

					if !slices.Contains(eligibleSpellCodes, spell.SpellCode) {
						return
					}

					if !sim.Proc(0.35, "Mirror Magic") {
						return
					}

					multiplier := 0.1
					if spell.SpellSchool.Matches(core.SpellSchoolFire) || spell.SpellSchool.Matches(core.SpellSchoolFrost) {
						multiplier = 0.2
					}

					mirrorDamage := result.Damage * multiplier

					if spell.SpellSchool.Matches(core.SpellSchoolArcane) {
						arcaneDamage = mirrorDamage
						arcaneProc.Cast(sim, result.Target)
					} else if spell.SpellSchool.Matches(core.SpellSchoolFire) {
						fireDamage = mirrorDamage
						fireProc.Cast(sim, result.Target)
					} else if spell.SpellSchool.Matches(core.SpellSchoolFrost) {
						frostDamage = mirrorDamage
						frostProc.Cast(sim, result.Target)
					}
				},
			})
		},
		// Your spell critical strikes conjure a magical barrier that absorbs 350 damage. While the barrier holds, the damage you deal with magical spells and
		// effects is increased by up to 42 and the threat you generate is reduced by 15%.
		5: func(agent core.Agent) {
			mage := agent.(MageAgent).GetMage()

			barrierSpell := mage.GetOrRegisterSpell(core.SpellConfig{
				ActionID:    core.ActionID{SpellID: 52585},
				SpellSchool: core.SpellSchoolArcane,
				ProcMask:    core.ProcMaskEmpty,
				Flags:       core.SpellFlagNoOnCastComplete | core.SpellFlagPassiveSpell | core.SpellFlagHelpful,

				DamageMultiplier: 1,
				ThreatMultiplier: 1,

				Shield: core.ShieldConfig{
					Aura: core.Aura{
						Label:    "Guardian's Barrier",
						Duration: time.Second * 10,
						OnGain: func(aura *core.Aura, sim *core.Simulation) {
							mage.AddStatDynamic(sim, stats.SpellDamage, 42)
							mage.PseudoStats.ThreatMultiplier /= 1.15
						},
						OnExpire: func(aura *core.Aura, sim *core.Simulation) {
							mage.AddStatDynamic(sim, stats.SpellDamage, -42)
							mage.PseudoStats.ThreatMultiplier *= 1.15
						},
					},
				},
			})

			mage.RegisterAura(core.Aura{
				Label:    "Guardian's Barrier",
				Duration: core.NeverExpires,
				OnReset: func(aura *core.Aura, sim *core.Simulation) {
					aura.Activate(sim)
				},
				OnSpellHitDealt: func(aura *core.Aura, sim *core.Simulation, spell *core.Spell, result *core.SpellResult) {
					if !result.Landed() || !spell.Flags.Matches(SpellFlagMage) {
						return
					}
					if !result.DidCrit() {
						return
					}
					barrierSpell.Shield(&mage.Unit).Apply(sim, 350)
				},
			})
		},
	},
})

var ItemSetVestmentsOfTheGuardian = core.NewItemSet(core.ItemSet{
	Name: "Vestments of the Guardian",
	ID:   685,
	Bonuses: map[int32]core.ApplyEffect{
		// Increases the chance for Resonance Cascade to trigger by 5%.
		3: func(agent core.Agent) {
			// Implemented in talents.go
		},
		// Reduce the mana cost of your spells by 100% for 6s after Presence of Mind is consumed.
		5: func(agent core.Agent) {
			// Implemented in talents.go
		},
	},
})
